export default [
  {
    title: 'Home',
    to: { name: 'root' },
    icon: { icon: 'tabler-smart-home' },
  },
  {
    title: 'Usuários',
    icon: { icon: 'tabler-users-group' },
    to: 'users',
    action: 'list',
    subject: 'users',
  },
  {
    title: 'Controle de Acesso',
    icon: { icon: 'tabler-smart-home' },
    children: [
      { title: 'Perfis', to: 'acesso-perfis' },
      { title: 'Permissões', to: 'acesso-permissoes' },
    ],
  },
  {
    title: 'Endereços',
    icon: { icon: 'tabler-home-2' },
    to: 'endereco',
    action: 'list',
    subject: 'endereco',
  },
  {
    title: 'Lojas',
    icon: { icon: 'tabler-building-store' },
    to: 'loja',
    action: 'list',
    subject: 'loja',
  },
  {
    title: 'Produto',
    icon: { icon: 'tabler-shopping-cart' },
    to: 'produto',
    action: 'list',
    subject: 'produto',
  },
  {
    title: 'Noticias',
    icon: { icon: 'tabler-news' },
    to: 'noticias',
    action: 'list',
    subject: 'noticias',
  },
  {
    title: 'Promoções',
    icon: { icon: 'tabler-basket-star' },
    to: 'promocao',
    action: 'list',
    subject: 'promocao',
  },
  // {
  //   title: 'Pedido',
  //   icon: { icon: 'tabler-template' },
  //   to: 'pedido',
  //   action: 'list',
  //   subject: 'pedido',
  // },
  // {
  //   title: 'Avaliacao',
  //   icon: { icon: 'tabler-template' },
  //   to: 'avaliacao',
  //   action: 'list',
  //   subject: 'avaliacao',
  // },
{
                    title: 'Transacoes financeiras',
                    icon: { icon: 'tabler-template' },
                    to: 'transacoes-financeiras',
                    action: 'list',
                    subject: 'transacoes-financeiras',
                },
]