<?php

return [
    'auth' => [
        'auth read',
    ],
    'manage' => [
        'all manage',
    ],
    'user' => [
        'user read',
        'user list',
        'user create',
        'user edit',
        'user delete',
    ],
    'profile' => [
        'profile read',
        'profile edit',
    ],
    'roles' => [
        'roles read',
        'roles list',
        'roles create',
        'roles edit',
        'roles delete',
    ],
    'permission' => [
        'permission read',
        'permission list',
        'permission create',
        'permission edit',
        'permission delete',
    ],
    'endereco' => [
        'endereco read',
        'endereco create',
        'endereco delete',
        'endereco list',
        'endereco edit',
        'endereco block',
        'endereco manage',
    ],
    'loja' => [
        'loja read',
        'loja create',
        'loja delete',
        'loja list',
        'loja edit',
        'loja block',
        'loja manage',
    ],
    'produto' => [
        'produto read',
        'produto create',
        'produto delete',
        'produto list',
        'produto edit',
        'produto block',
        'produto manage',
    ],
    'produto-aprovacao' => [
        'produto-aprovacao read',
        'produto-aprovacao list',
        'produto-aprovacao edit',
    ],
    'loja-produto' => [
        'loja-produto read',
        'loja-produto list',
        'loja-produto create',
        'loja-produto edit',
        'loja-produto delete',
    ],
    'noticias' => [
        'noticias read',
        'noticias create',
        'noticias delete',
        'noticias list',
        'noticias edit',
        'noticias block',
        'noticias manage',
    ],
    'promocao' => [
        'promocao read',
        'promocao create',
        'promocao delete',
        'promocao list',
        'promocao edit',
        'promocao block',
        'promocao manage',
    ],
    'pedido' => [
        'pedido read',
        'pedido create',
        'pedido delete',
        'pedido list',
        'pedido edit',
        'pedido block',
        'pedido manage',
    ],
    'item-pedido' => [
        'item-pedido read',
        'item-pedido create',
        'item-pedido delete',
        'item-pedido list',
        'item-pedido edit',
        'item-pedido block',
        'item-pedido manage',
    ],
    'avaliacao' => [
        'avaliacao read',
        'avaliacao create',
        'avaliacao delete',
        'avaliacao list',
        'avaliacao edit',
        'avaliacao block',
        'avaliacao manage',
    ],
    'transacoes-financeiras' => [
        'transacoes-financeiras read',
        'transacoes-financeiras create',
        'transacoes-financeiras delete',
        'transacoes-financeiras list',
        'transacoes-financeiras edit',
        'transacoes-financeiras block',
        'transacoes-financeiras manage',
    ],
    'destaque' => [
        'destaque read',
        'destaque create',
        'destaque delete',
        'destaque list',
        'destaque edit',
        'destaque block',
        'destaque manage',
    ],
    'configuracao' => [
        'configuracao read',
        'configuracao create',
        'configuracao delete',
        'configuracao list',
        'configuracao edit',
        'configuracao block',
        'configuracao manage',
    ],
    'dashboard' => [
        'dashboard read',
    ],
    'relatorios' => [
        'relatorios read',
    ],
    'audit' => [
        'audit read',
    ],
    'entrega' => [
        'entrega read',
        'entrega list',
        'entrega edit',
        'entrega manage',
    ],
];
