<?php

return [
    'auth' => [
        'auth read',
    ],
    'manage' => [
        'all manage',
    ],
    'users' => [
        'users read',
        'users list',
        'users create',
        'users edit',
        'users delete',
    ],
    'profile' => [
        'profile read',
        'profile edit',
    ],
    'roles' => [
        'roles read',
        'roles list',
        'roles create',
        'roles edit',
        'roles delete',
    ],
    'permission' => [
        'permission read',
        'permission list',
        'permission create',
        'permission edit',
        'permission delete',
    ],
    'endereco' => [
        'endereco read',
        'endereco create',
        'endereco delete',
        'endereco list',
        'endereco edit',
        'endereco block',
        'endereco manage',
    ],
    'loja' => [
        'loja read',
        'loja create',
        'loja delete',
        'loja list',
        'loja edit',
        'loja block',
        'loja manage',
    ],
    'produto' => [
        'produto read',
        'produto create',
        'produto delete',
        'produto list',
        'produto edit',
        'produto block',
        'produto manage',
    ],
    'noticias' => [
        'noticias read',
        'noticias create',
        'noticias delete',
        'noticias list',
        'noticias edit',
        'noticias block',
        'noticias manage',
    ],
    'promocao' => [
        'promocao read',
        'promocao create',
        'promocao delete',
        'promocao list',
        'promocao edit',
        'promocao block',
        'promocao manage',
    ],
    'pedido' => [
        'pedido read',
        'pedido create',
        'pedido delete',
        'pedido list',
        'pedido edit',
        'pedido block',
        'pedido manage',
    ],
    'itempedido' => [
        'itempedido read',
        'itempedido create',
        'itempedido delete',
        'itempedido list',
        'itempedido edit',
        'itempedido block',
        'itempedido manage',
    ],
    'avaliacao' => [
        'avaliacao read',
        'avaliacao create',
        'avaliacao delete',
        'avaliacao list',
        'avaliacao edit',
        'avaliacao block',
        'avaliacao manage',
    ],
    'transacoesfinanceiras' => [
        'transacoesfinanceiras read',
        'transacoesfinanceiras create',
        'transacoesfinanceiras delete',
        'transacoesfinanceiras list',
        'transacoesfinanceiras edit',
        'transacoesfinanceiras block',
        'transacoesfinanceiras manage',
    ],
];
